import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import TopBar from '@/components/TopBar';
import Footer from '@/components/Footer/Footer';
import { DarkModeProvider } from '@/components/dark-mode';
import SectionNavigationProvider from '@/components/section-navigation/SectionNavigationProvider';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/autoplay';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Joseph Lepley\'s Portfolio',
    default: 'Joseph Lepley\'s Portfolio',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DarkModeProvider>
          <SectionNavigationProvider>
            <TopBar />
            <div className="shadow-4xl mx-auto flex-1 md:container">
              {children}
            </div>
            <Footer />
          </SectionNavigationProvider>
        </DarkModeProvider>
      </body>
    </html>
  );
}
